<?php
/**
 * Texte der ElTouro App. Styleguide: duzen, kein Gendern.
 * Vokabular: Herde/crew, Leitstier/crew lead, Tour/route, Ausfahrt/ride.
 * Jeder Schlüssel in BEIDEN Sprachen. Das Admin-Backend ist bewusst nur deutsch.
 */
return [
'de' => [
    'nav.skip' => 'Zum Inhalt springen', 'nav.haupt' => 'Hauptnavigation', 'nav.sprache' => 'Sprache',
    'nav.herden' => 'Herden', 'nav.profil' => 'Profil', 'nav.admin' => 'Admin',
    'nav.login' => 'Anmelden', 'nav.logout' => 'Abmelden', 'nav.registrieren' => 'Registrieren',
    'env.hinweis' => 'Vorabversion, Daten können jederzeit zurückgesetzt werden',

    'fehler.csrf' => 'Die Sitzung ist abgelaufen. Bitte lade die Seite neu und versuch es noch einmal.',
    'fehler.allgemein' => 'Das hat gerade nicht geklappt. Bitte versuch es noch einmal.',
    'fehler.nicht_gefunden' => 'Nicht gefunden.',

    'zugang.titel' => 'Vorabzugang', 'zugang.text' => 'ElTouro ist hier noch in Entwicklung. Mit dem Tester-Passwort kommst du rein.',
    'zugang.passwort' => 'Tester-Passwort', 'zugang.knopf' => 'Reinlassen', 'zugang.falsch' => 'Das Passwort stimmt nicht.',

    'start.titel' => 'Start', 'start.hallo' => 'Hallo {name}!',
    'start.meine_herden' => 'Deine Herden', 'start.keine_herden' => 'Du bist noch in keiner Herde. Schau dich um oder gründe deine eigene.',
    'start.gast_titel' => 'Finde deine Tour. Finde deine Herde.',
    'start.gast_text' => 'Melde dich an, um Herden zu finden und gemeinsam loszufahren.',

    'reg.titel' => 'Registrieren', 'reg.email' => 'E-Mail-Adresse', 'reg.name' => 'Anzeigename',
    'reg.name_hint' => '3 bis 30 Zeichen: Buchstaben, Ziffern, Punkt, Bindestrich, Unterstrich. So sehen dich andere.',
    'reg.geburt' => 'Geburtsdatum', 'reg.geburt_hint' => 'Du musst mindestens {alter} Jahre alt sein. Andere sehen dein Geburtsdatum nicht.',
    'reg.passwort' => 'Passwort', 'reg.passwort_hint' => 'Mindestens 10 Zeichen.',
    'reg.agb' => 'Ich akzeptiere die {agb} und habe die {ds} gelesen.',
    'reg.knopf' => 'Konto anlegen', 'reg.zu' => 'Die Registrierung ist gerade geschlossen.',
    'reg.fehler_email' => 'Bitte gib eine gültige E-Mail-Adresse ein.',
    'reg.fehler_name' => 'Der Anzeigename passt nicht zu den Regeln.',
    'reg.fehler_name_vergeben' => 'Dieser Anzeigename ist schon vergeben.',
    'reg.fehler_alter' => 'Für ElTouro musst du mindestens {alter} Jahre alt sein.',
    'reg.fehler_passwort' => 'Das Passwort ist zu kurz.',
    'reg.fehler_agb' => 'Bitte bestätige die Nutzungsbedingungen.',
    'reg.fertig' => 'Fast geschafft: Wir haben dir eine E-Mail geschickt. Klick auf den Link darin, um dein Konto zu aktivieren.',

    'best.ok' => 'Deine E-Mail-Adresse ist bestätigt. Willkommen bei ElTouro!',
    'best.fehler' => 'Dieser Link ist abgelaufen oder wurde schon benutzt.',

    'login.titel' => 'Anmelden', 'login.knopf' => 'Anmelden', 'login.vergessen' => 'Passwort vergessen?',
    'login.fehler' => 'E-Mail-Adresse oder Passwort stimmen nicht, oder das Konto ist noch nicht bestätigt.',
    'login.zu_viele' => 'Zu viele Versuche. Bitte warte ein paar Minuten.',
    'logout.ok' => 'Du bist abgemeldet.',

    'pw.titel' => 'Passwort vergessen', 'pw.text' => 'Gib deine E-Mail-Adresse ein. Wenn es dazu ein Konto gibt, schicken wir dir einen Link zum Zurücksetzen.',
    'pw.knopf' => 'Link schicken', 'pw.gesendet' => 'Wenn es ein Konto mit dieser Adresse gibt, ist der Link unterwegs.',
    'pw.neu_titel' => 'Neues Passwort', 'pw.neu_knopf' => 'Passwort speichern', 'pw.neu_ok' => 'Dein Passwort ist geändert. Du bist angemeldet.',

    'mail.verify_betreff' => 'Bestätige dein ElTouro-Konto',
    'mail.verify_text' => "Hallo {name},\n\nbitte bestätige deine E-Mail-Adresse, um dein ElTouro-Konto zu aktivieren:\n\n{link}\n\nDer Link ist 48 Stunden gültig. Wenn du dich nicht registriert hast, ignoriere diese Mail.\n\nDein ElTouro-Team",
    'mail.reset_betreff' => 'Dein ElTouro-Passwort zurücksetzen',
    'mail.reset_text' => "Hallo {name},\n\nhier kannst du ein neues Passwort festlegen:\n\n{link}\n\nDer Link ist 1 Stunde gültig. Wenn du das nicht angefordert hast, ignoriere diese Mail – dein Passwort bleibt unverändert.\n\nDein ElTouro-Team",

    'profil.titel' => 'Dein Profil', 'profil.bio' => 'Über dich', 'profil.region' => 'Wo fährst du meistens?',
    'profil.sprache' => 'Sprache', 'profil.knopf' => 'Speichern', 'profil.ok' => 'Gespeichert.',

    'herden.titel' => 'Herden', 'herden.suche' => 'Herde oder Region suchen', 'herden.suchen' => 'Suchen',
    'herden.neu' => 'Eigene Herde gründen', 'herden.keine' => 'Keine Herden gefunden.',
    'herden.mitglieder' => '{n} Mitglieder', 'herden.meine' => 'Deine Herden', 'herden.entdecken' => 'Herden entdecken',

    'herde.name' => 'Name der Herde', 'herde.beschreibung' => 'Beschreibung', 'herde.region' => 'Region',
    'herde.sichtbarkeit' => 'Sichtbarkeit', 'herde.listed' => 'Auffindbar – erscheint in der Suche', 'herde.secret' => 'Geheim – nur per Einladungslink zu finden',
    'herde.beitritt' => 'Beitritt', 'herde.open' => 'Offen – jeder kann direkt beitreten', 'herde.request' => 'Geschlossen – der Leitstier bestätigt Anfragen', 'herde.invite' => 'Nur mit Einladungslink',
    'herde.gruenden' => 'Herde gründen', 'herde.gegruendet' => 'Deine Herde ist gegründet. Du bist ihr Leitstier.',
    'herde.fehler_name' => 'Bitte gib einen Namen mit 3 bis 60 Zeichen ein.',
    'herde.beitreten' => 'Beitreten', 'herde.anfragen' => 'Beitritt anfragen', 'herde.verlassen' => 'Herde verlassen',
    'herde.beigetreten' => 'Willkommen in der Herde!', 'herde.angefragt' => 'Deine Anfrage ist beim Leitstier.',
    'herde.anfrage_offen' => 'Deine Anfrage wartet auf Bestätigung.', 'herde.verlassen_ok' => 'Du hast die Herde verlassen.',
    'herde.letzter_leitstier' => 'Du bist der einzige Leitstier. Ernenne erst jemand anderen, bevor du gehst.',
    'herde.nur_einladung' => 'Dieser Herde kannst du nur mit einem Einladungslink beitreten.',
    'herde.mitglieder_titel' => 'Mitglieder', 'herde.mitglieder_nur' => 'Die Mitgliederliste sehen nur Mitglieder.',
    'herde.leitstier' => 'Leitstier', 'herde.du' => 'du',
    'herde.anfragen_titel' => 'Offene Anfragen', 'herde.annehmen' => 'Annehmen', 'herde.ablehnen' => 'Ablehnen',
    'herde.entfernen' => 'Entfernen', 'herde.befoerdern' => 'Zum Leitstier machen',
    'herde.einladung' => 'Einladungslink', 'herde.einladung_hint' => 'Wer diesen Link hat, kann die Herde sehen und beitreten.',
    'herde.einladung_neu' => 'Neuen Link erzeugen (alter wird ungültig)',
    'herde.einstellungen' => 'Einstellungen der Herde', 'herde.speichern' => 'Speichern', 'herde.gespeichert' => 'Gespeichert.',
    'herde.ausfahrten' => 'Touren & Ausfahrten', 'herde.tour_neu' => 'Tour für diese Herde planen', 'herde.ausfahrten_bald' => 'Termine mit Treffpunkt und Anmeldung kommen als Nächstes. Touren der Herde:',

    'nav.touren' => 'Touren', 'nav.forum' => 'Forum',

    'touren.titel' => 'Touren', 'touren.meine' => 'Deine Touren', 'touren.herden' => 'Touren deiner Herden',
    'touren.oeffentlich' => 'Öffentliche Touren', 'touren.keine' => 'Hier ist noch nichts.',
    'tour.neu' => 'Tour planen', 'tour.bearbeiten' => 'Tour bearbeiten', 'tour.speichern' => 'Tour speichern',
    'tour.gespeichert' => 'Tour gespeichert.', 'tour.geloescht' => 'Tour gelöscht.', 'tour.loeschen' => 'Tour löschen',
    'tour.titel' => 'Name der Tour', 'tour.beschreibung' => 'Beschreibung', 'tour.herde' => 'Herde',
    'tour.schwierigkeit' => 'Schwierigkeit', 'tour.schwierigkeit_hint' => 'Deine Einschätzung für andere Fahrer.',
    'tour.d_easy' => 'Einfach', 'tour.d_moderate' => 'Mittel', 'tour.d_demanding' => 'Anspruchsvoll',
    'tour.stil' => 'Fahrstil', 'tour.s_relaxed' => 'Gemütlich', 'tour.s_social' => 'Gesellig', 'tour.s_sporty' => 'Sportlich',
    'tour.regelwerk' => 'Verkehrsregeln', 'tour.r_ekfv' => 'Aktuelle eKFV', 'tour.r_ekfv2027' => 'Ab 1. März 2027',
    'tour.sichtbarkeit' => 'Wer sieht die Tour?', 'tour.v_private' => 'Nur ich', 'tour.v_group' => 'Meine Herde', 'tour.v_public' => 'Alle angemeldeten Fahrer',
    'tour.fehler_titel' => 'Bitte gib der Tour einen Namen (mindestens 3 Zeichen).',
    'tour.fehler_route' => 'Die Route ist unvollständig. Setz mindestens zwei Punkte und warte, bis sie berechnet ist.',
    'tour.fehler_herde' => 'Für „Meine Herde“ wähle bitte eine Herde aus.',
    'tour.von' => 'von {name}', 'tour.start' => 'Start', 'tour.ziel' => 'Ziel',
    'tour.laenge' => 'Länge', 'tour.anstieg' => 'Anstieg',
    'tour.einschaetzung' => 'Schwierigkeit und Fahrstil sind die Einschätzung des Erstellers.',
    'tour.freihand_warnung' => '{p} % dieser Tour sind von Hand verbunden und nicht auf E-Scooter-Tauglichkeit geprüft (rot gestrichelt).',
    'tour.vor_ort' => 'Die Route ist ein Vorschlag. Vor Ort gelten immer die Verkehrszeichen.',
    'tour.gpx' => 'GPX herunterladen',

    'planer.anleitung' => 'Klick in die Karte setzt einen Wegpunkt. Punkte lassen sich verschieben; ein Klick auf einen Punkt entfernt ihn.',
    'planer.rueckgaengig' => 'Letzten Punkt entfernen', 'planer.rundtour' => 'Zurück zum Start', 'planer.standort' => 'Mein Standort', 'planer.leeren' => 'Alle Punkte löschen',
    'planer.punkt' => 'Wegpunkt', 'planer.rechne' => 'Route wird berechnet …', 'planer.fertig' => 'Route berechnet.',
    'planer.fehler' => 'Die Route konnte gerade nicht berechnet werden. Versuch es gleich noch einmal.',
    'planer.hinweis_ohne_router' => 'Routing ist noch nicht angebunden – die Punkte werden gerade verbunden (Freihand).',
    'planer.hinweis_teilweise_freihand' => 'Ein Teil lässt sich nicht über erlaubte Wege führen und ist rot gestrichelt verbunden.',
    'planer.leer' => 'Setz mindestens zwei Punkte.', 'planer.kennzahl' => '{km} km · {n} Wegpunkte', 'planer.freihand_anteil' => '{p} % freihand',
    'planer.standort_fehler' => 'Standort nicht verfügbar.',

    'forum.titel' => 'Forum', 'forum.intro' => 'Austausch unter E-Scooter-Fahrern: Fragen, Tipps, Touren und Feedback zu ElTouro.',
    'forum.themen' => '{n} Themen', 'forum.antworten' => '{n} Antworten', 'forum.von' => 'von {name}',
    'forum.neues_thema' => 'Neues Thema', 'forum.keine_themen' => 'Noch keine Themen. Fang an!',
    'forum.angepinnt' => 'Angepinnt', 'forum.gesperrt' => 'Geschlossen', 'forum.gesperrt_text' => 'Dieses Thema ist geschlossen.',
    'forum.betreff' => 'Betreff', 'forum.text' => 'Dein Beitrag', 'forum.veroeffentlichen' => 'Veröffentlichen',
    'forum.antworten_titel' => 'Antworten', 'forum.senden' => 'Antwort senden', 'forum.loeschen' => 'Löschen',
    'forum.geloescht' => 'Dieser Beitrag wurde gelöscht.', 'forum.seiten' => 'Seiten',
    'forum.format' => 'Absätze mit Leerzeile, **fett**, - Liste, [Link](https://…).',
    'forum.fehler_titel' => 'Der Betreff braucht mindestens 5 Zeichen.', 'forum.fehler_text' => 'Der Beitrag muss zwischen 2 und {max} Zeichen lang sein.',
    'forum.zu_schnell' => 'Nicht so schnell – warte ein paar Sekunden bis zum nächsten Beitrag.',
    'forum.m_anpinnen' => 'Anpinnen', 'forum.m_lospinnen' => 'Nicht mehr anpinnen', 'forum.m_sperren' => 'Schließen', 'forum.m_entsperren' => 'Wieder öffnen', 'forum.m_loeschen' => 'Thema löschen',

    'melden.link' => 'Melden', 'melden.titel' => 'Inhalt melden',
    'melden.text' => 'Verstößt etwas gegen Gesetze oder unsere Nutzungsbedingungen? Beschreib kurz, was nicht in Ordnung ist. Wir prüfen jede Meldung.',
    'melden.grund' => 'Was ist das Problem?', 'melden.senden' => 'Meldung abschicken',
    'melden.fehler' => 'Bitte beschreib das Problem in mindestens 10 Zeichen.', 'melden.danke' => 'Danke, deine Meldung ist bei uns angekommen.',
    'traenke.titel' => 'Tränke', 'traenke.oeffnen' => 'Zur Tränke',
    'traenke.intro' => 'Hier trifft sich eure Herde: Absprachen, Fragen, Foto-Links, Geschichten von der letzten Tour. Nur Mitglieder sehen, was hier steht.',
    'traenke.nur_mitglieder' => 'Die Tränke ist nur für Mitglieder dieser Herde.',
    'traenke.neues_thema' => 'Neues Thema', 'traenke.leer' => 'Noch still an der Tränke. Mach den Anfang!',
    'traenke.fehler_titel' => 'Der Betreff braucht mindestens 3 Zeichen.',
    'traenke.neu' => 'neu', 'traenke.n_neu' => '{n} neu', 'traenke.beitraege' => '{n} Beiträge',
    'traenke.ungelesen_ab' => 'Neu seit deinem letzten Besuch', 'traenke.bearbeitet' => 'bearbeitet',
    'traenke.geloescht' => 'Beitrag gelöscht', 'traenke.gefaellt' => 'Gefällt mir', 'traenke.antworten' => 'Antworten', 'traenke.loeschen' => 'Löschen',
    'traenke.platzhalter' => 'Schreib etwas an die Herde …', 'traenke.senden_hint' => 'Strg + Enter zum Senden',
    'traenke.antwort_weg' => 'Antwort-Bezug entfernen',
    'traenke.js_neue_beitraege' => '{n} neue Beiträge – anzeigen', 'traenke.js_antwort_an' => 'Antwort an {name}',
    'traenke.js_loeschen_frage' => 'Diesen Beitrag wirklich löschen?', 'traenke.js_fehler' => 'Das hat nicht geklappt. Bitte versuch es noch einmal.',
    'traenke.js_laedt' => 'Lädt …', 'traenke.js_keine_mehr' => 'Das war alles.',
    'zeit.jetzt' => 'gerade eben', 'zeit.min' => 'vor {n} Min.', 'zeit.std' => 'vor {n} Std.', 'zeit.tage' => 'vor {n} Tagen',
    'footer.impressum' => 'Impressum', 'footer.datenschutz' => 'Datenschutz', 'footer.nutzungsbedingungen' => 'Nutzungsbedingungen',
    'seite.leer' => 'Diese Seite wird gerade vorbereitet.',
],
'en' => [
    'nav.skip' => 'Skip to content', 'nav.haupt' => 'Main navigation', 'nav.sprache' => 'Language',
    'nav.herden' => 'Crews', 'nav.profil' => 'Profile', 'nav.admin' => 'Admin',
    'nav.login' => 'Log in', 'nav.logout' => 'Log out', 'nav.registrieren' => 'Sign up',
    'env.hinweis' => 'Preview version, data may be reset at any time',

    'fehler.csrf' => 'Your session expired. Please reload the page and try again.',
    'fehler.allgemein' => 'That didn’t work just now. Please try again.',
    'fehler.nicht_gefunden' => 'Not found.',

    'zugang.titel' => 'Preview access', 'zugang.text' => 'ElTouro is still in development here. Enter the tester password to get in.',
    'zugang.passwort' => 'Tester password', 'zugang.knopf' => 'Let me in', 'zugang.falsch' => 'Wrong password.',

    'start.titel' => 'Home', 'start.hallo' => 'Hi {name}!',
    'start.meine_herden' => 'Your crews', 'start.keine_herden' => 'You’re not in a crew yet. Look around or start your own.',
    'start.gast_titel' => 'Find your ride. Find your crew.',
    'start.gast_text' => 'Log in to find crews and ride out together.',

    'reg.titel' => 'Sign up', 'reg.email' => 'Email address', 'reg.name' => 'Display name',
    'reg.name_hint' => '3 to 30 characters: letters, digits, dot, hyphen, underscore. This is how others see you.',
    'reg.geburt' => 'Date of birth', 'reg.geburt_hint' => 'You must be at least {alter} years old. Others can’t see your date of birth.',
    'reg.passwort' => 'Password', 'reg.passwort_hint' => 'At least 10 characters.',
    'reg.agb' => 'I accept the {agb} and have read the {ds}.',
    'reg.knopf' => 'Create account', 'reg.zu' => 'Sign-up is currently closed.',
    'reg.fehler_email' => 'Please enter a valid email address.',
    'reg.fehler_name' => 'The display name doesn’t match the rules.',
    'reg.fehler_name_vergeben' => 'This display name is already taken.',
    'reg.fehler_alter' => 'You must be at least {alter} years old to use ElTouro.',
    'reg.fehler_passwort' => 'The password is too short.',
    'reg.fehler_agb' => 'Please accept the terms of use.',
    'reg.fertig' => 'Almost there: we’ve sent you an email. Click the link inside to activate your account.',

    'best.ok' => 'Your email address is confirmed. Welcome to ElTouro!',
    'best.fehler' => 'This link has expired or was already used.',

    'login.titel' => 'Log in', 'login.knopf' => 'Log in', 'login.vergessen' => 'Forgot your password?',
    'login.fehler' => 'Email or password is wrong, or the account isn’t confirmed yet.',
    'login.zu_viele' => 'Too many attempts. Please wait a few minutes.',
    'logout.ok' => 'You’re logged out.',

    'pw.titel' => 'Forgot password', 'pw.text' => 'Enter your email address. If there’s an account for it, we’ll send you a reset link.',
    'pw.knopf' => 'Send link', 'pw.gesendet' => 'If there’s an account with this address, the link is on its way.',
    'pw.neu_titel' => 'New password', 'pw.neu_knopf' => 'Save password', 'pw.neu_ok' => 'Your password has been changed. You’re logged in.',

    'mail.verify_betreff' => 'Confirm your ElTouro account',
    'mail.verify_text' => "Hi {name},\n\nplease confirm your email address to activate your ElTouro account:\n\n{link}\n\nThe link is valid for 48 hours. If you didn’t sign up, just ignore this email.\n\nThe ElTouro team",
    'mail.reset_betreff' => 'Reset your ElTouro password',
    'mail.reset_text' => "Hi {name},\n\nyou can set a new password here:\n\n{link}\n\nThe link is valid for 1 hour. If you didn’t request this, ignore this email – your password stays the same.\n\nThe ElTouro team",

    'profil.titel' => 'Your profile', 'profil.bio' => 'About you', 'profil.region' => 'Where do you usually ride?',
    'profil.sprache' => 'Language', 'profil.knopf' => 'Save', 'profil.ok' => 'Saved.',

    'herden.titel' => 'Crews', 'herden.suche' => 'Search crew or area', 'herden.suchen' => 'Search',
    'herden.neu' => 'Start your own crew', 'herden.keine' => 'No crews found.',
    'herden.mitglieder' => '{n} members', 'herden.meine' => 'Your crews', 'herden.entdecken' => 'Discover crews',

    'herde.name' => 'Crew name', 'herde.beschreibung' => 'Description', 'herde.region' => 'Area',
    'herde.sichtbarkeit' => 'Visibility', 'herde.listed' => 'Listed – shows up in search', 'herde.secret' => 'Secret – only findable via invite link',
    'herde.beitritt' => 'Joining', 'herde.open' => 'Open – anyone can join right away', 'herde.request' => 'Closed – the crew lead approves requests', 'herde.invite' => 'Invite link only',
    'herde.gruenden' => 'Start crew', 'herde.gegruendet' => 'Your crew is live. You’re its crew lead.',
    'herde.fehler_name' => 'Please enter a name with 3 to 60 characters.',
    'herde.beitreten' => 'Join', 'herde.anfragen' => 'Request to join', 'herde.verlassen' => 'Leave crew',
    'herde.beigetreten' => 'Welcome to the crew!', 'herde.angefragt' => 'Your request is with the crew lead.',
    'herde.anfrage_offen' => 'Your request is waiting for approval.', 'herde.verlassen_ok' => 'You left the crew.',
    'herde.letzter_leitstier' => 'You’re the only crew lead. Make someone else crew lead before you leave.',
    'herde.nur_einladung' => 'You can only join this crew with an invite link.',
    'herde.mitglieder_titel' => 'Members', 'herde.mitglieder_nur' => 'Only members can see the member list.',
    'herde.leitstier' => 'Crew lead', 'herde.du' => 'you',
    'herde.anfragen_titel' => 'Open requests', 'herde.annehmen' => 'Accept', 'herde.ablehnen' => 'Decline',
    'herde.entfernen' => 'Remove', 'herde.befoerdern' => 'Make crew lead',
    'herde.einladung' => 'Invite link', 'herde.einladung_hint' => 'Anyone with this link can see and join the crew.',
    'herde.einladung_neu' => 'Create new link (old one stops working)',
    'herde.einstellungen' => 'Crew settings', 'herde.speichern' => 'Save', 'herde.gespeichert' => 'Saved.',
    'herde.ausfahrten' => 'Routes & rides', 'herde.tour_neu' => 'Plan a route for this crew', 'herde.ausfahrten_bald' => 'Rides with a date, meeting point and sign-up are coming next. Routes of this crew:',

    'nav.touren' => 'Routes', 'nav.forum' => 'Forum',

    'touren.titel' => 'Routes', 'touren.meine' => 'Your routes', 'touren.herden' => 'Routes from your crews',
    'touren.oeffentlich' => 'Public routes', 'touren.keine' => 'Nothing here yet.',
    'tour.neu' => 'Plan a route', 'tour.bearbeiten' => 'Edit route', 'tour.speichern' => 'Save route',
    'tour.gespeichert' => 'Route saved.', 'tour.geloescht' => 'Route deleted.', 'tour.loeschen' => 'Delete route',
    'tour.titel' => 'Route name', 'tour.beschreibung' => 'Description', 'tour.herde' => 'Crew',
    'tour.schwierigkeit' => 'Difficulty', 'tour.schwierigkeit_hint' => 'Your assessment for other riders.',
    'tour.d_easy' => 'Easy', 'tour.d_moderate' => 'Moderate', 'tour.d_demanding' => 'Demanding',
    'tour.stil' => 'Riding style', 'tour.s_relaxed' => 'Relaxed', 'tour.s_social' => 'Social', 'tour.s_sporty' => 'Sporty',
    'tour.regelwerk' => 'Traffic rules', 'tour.r_ekfv' => 'Current German rules (eKFV)', 'tour.r_ekfv2027' => 'From 1 March 2027',
    'tour.sichtbarkeit' => 'Who can see it?', 'tour.v_private' => 'Only me', 'tour.v_group' => 'My crew', 'tour.v_public' => 'All logged-in riders',
    'tour.fehler_titel' => 'Please give the route a name (at least 3 characters).',
    'tour.fehler_route' => 'The route is incomplete. Set at least two points and wait until it’s calculated.',
    'tour.fehler_herde' => 'For “My crew”, please choose a crew.',
    'tour.von' => 'by {name}', 'tour.start' => 'Start', 'tour.ziel' => 'Finish',
    'tour.laenge' => 'Length', 'tour.anstieg' => 'Climb',
    'tour.einschaetzung' => 'Difficulty and riding style are the creator’s own assessment.',
    'tour.freihand_warnung' => '{p}% of this route is connected by hand and not checked for e-scooter suitability (red dashes).',
    'tour.vor_ort' => 'The route is a suggestion. Road signs on site always take priority.',
    'tour.gpx' => 'Download GPX',

    'planer.anleitung' => 'Click the map to add a waypoint. Drag points to move them; click a point to remove it.',
    'planer.rueckgaengig' => 'Remove last point', 'planer.rundtour' => 'Back to start', 'planer.standort' => 'My location', 'planer.leeren' => 'Clear all points',
    'planer.punkt' => 'Waypoint', 'planer.rechne' => 'Calculating route …', 'planer.fertig' => 'Route calculated.',
    'planer.fehler' => 'The route couldn’t be calculated just now. Please try again in a moment.',
    'planer.hinweis_ohne_router' => 'Routing isn’t connected yet – points are joined with straight lines (freehand).',
    'planer.hinweis_teilweise_freihand' => 'Part of the route can’t follow permitted paths and is joined with red dashes.',
    'planer.leer' => 'Set at least two points.', 'planer.kennzahl' => '{km} km · {n} waypoints', 'planer.freihand_anteil' => '{p}% freehand',
    'planer.standort_fehler' => 'Location not available.',

    'forum.titel' => 'Forum', 'forum.intro' => 'Talk with other e-scooter riders: questions, tips, rides and feedback on ElTouro.',
    'forum.themen' => '{n} topics', 'forum.antworten' => '{n} replies', 'forum.von' => 'by {name}',
    'forum.neues_thema' => 'New topic', 'forum.keine_themen' => 'No topics yet. Start one!',
    'forum.angepinnt' => 'Pinned', 'forum.gesperrt' => 'Closed', 'forum.gesperrt_text' => 'This topic is closed.',
    'forum.betreff' => 'Subject', 'forum.text' => 'Your post', 'forum.veroeffentlichen' => 'Publish',
    'forum.antworten_titel' => 'Reply', 'forum.senden' => 'Send reply', 'forum.loeschen' => 'Delete',
    'forum.geloescht' => 'This post was deleted.', 'forum.seiten' => 'Pages',
    'forum.format' => 'Blank line for paragraphs, **bold**, - list, [link](https://…).',
    'forum.fehler_titel' => 'The subject needs at least 5 characters.', 'forum.fehler_text' => 'Posts must be between 2 and {max} characters.',
    'forum.zu_schnell' => 'Not so fast – wait a few seconds before your next post.',
    'forum.m_anpinnen' => 'Pin', 'forum.m_lospinnen' => 'Unpin', 'forum.m_sperren' => 'Close', 'forum.m_entsperren' => 'Reopen', 'forum.m_loeschen' => 'Delete topic',

    'melden.link' => 'Report', 'melden.titel' => 'Report content',
    'melden.text' => 'Does something break the law or our terms of use? Briefly describe what’s wrong. We review every report.',
    'melden.grund' => 'What’s the problem?', 'melden.senden' => 'Send report',
    'melden.fehler' => 'Please describe the problem in at least 10 characters.', 'melden.danke' => 'Thanks, we’ve received your report.',
    'traenke.titel' => 'Crew talk', 'traenke.oeffnen' => 'Open crew talk',
    'traenke.intro' => 'Where your crew hangs out: plans, questions, photo links, stories from the last ride. Only members can see what’s here.',
    'traenke.nur_mitglieder' => 'Crew talk is only for members of this crew.',
    'traenke.neues_thema' => 'New topic', 'traenke.leer' => 'All quiet so far. Start the conversation!',
    'traenke.fehler_titel' => 'The subject needs at least 3 characters.',
    'traenke.neu' => 'new', 'traenke.n_neu' => '{n} new', 'traenke.beitraege' => '{n} posts',
    'traenke.ungelesen_ab' => 'New since your last visit', 'traenke.bearbeitet' => 'edited',
    'traenke.geloescht' => 'Post deleted', 'traenke.gefaellt' => 'Like', 'traenke.antworten' => 'Reply', 'traenke.loeschen' => 'Delete',
    'traenke.platzhalter' => 'Write something to your crew …', 'traenke.senden_hint' => 'Ctrl + Enter to send',
    'traenke.antwort_weg' => 'Remove reply reference',
    'traenke.js_neue_beitraege' => '{n} new posts – show', 'traenke.js_antwort_an' => 'Replying to {name}',
    'traenke.js_loeschen_frage' => 'Really delete this post?', 'traenke.js_fehler' => 'That didn’t work. Please try again.',
    'traenke.js_laedt' => 'Loading …', 'traenke.js_keine_mehr' => 'That’s everything.',
    'zeit.jetzt' => 'just now', 'zeit.min' => '{n} min ago', 'zeit.std' => '{n} h ago', 'zeit.tage' => '{n} days ago',
    'footer.impressum' => 'Legal notice', 'footer.datenschutz' => 'Privacy', 'footer.nutzungsbedingungen' => 'Terms of use',
    'seite.leer' => 'This page is being prepared.',
],
];
