<?php
/**
 * UI texts of the ElTouro app. Style guide: informal "du", no gendering.
 * Vocabulary: Herde/crew, Leitstier/crew lead, Tour/route, Ausfahrt/ride, Tränke/crew talk.
 * Every key in BOTH languages. The admin backend is German only on purpose.
 * Nothing may follow the closing "];" – otherwise the whole app breaks.
 */
return [
'de' => [
    'nav.skip' => 'Zum Inhalt springen', 'nav.main' => 'Hauptnavigation', 'nav.language' => 'Sprache',
    'nav.crews' => 'Herden', 'nav.profile' => 'Profil', 'nav.admin' => 'Admin',
    'nav.login' => 'Anmelden', 'nav.logout' => 'Abmelden', 'nav.register' => 'Registrieren',
    'nav.tours' => 'Touren', 'nav.forum' => 'Forum',
    'env.notice' => 'Vorabversion, Daten können jederzeit zurückgesetzt werden',

    'error.csrf' => 'Die Sitzung ist abgelaufen. Bitte lade die Seite neu und versuch es noch einmal.',
    'error.general' => 'Das hat gerade nicht geklappt. Bitte versuch es noch einmal.',
    'error.not_found' => 'Nicht gefunden.',

    'access.title' => 'Vorabzugang', 'access.text' => 'ElTouro ist hier noch in Entwicklung. Mit dem Tester-Passwort kommst du rein.',
    'access.password' => 'Tester-Passwort', 'access.button' => 'Reinlassen', 'access.wrong' => 'Das Passwort stimmt nicht.',

    'home.title' => 'Start', 'home.hello' => 'Hallo {name}!',
    'home.my_crews' => 'Deine Herden', 'home.no_crews' => 'Du bist noch in keiner Herde. Schau dich um oder gründe deine eigene.',
    'home.guest_title' => 'Finde deine Tour. Finde deine Herde.',
    'home.guest_text' => 'Melde dich an, um Herden zu finden und gemeinsam loszufahren.',

    'register.title' => 'Registrieren', 'register.email' => 'E-Mail-Adresse', 'register.name' => 'Anzeigename',
    'register.name_hint' => '3 bis 30 Zeichen: Buchstaben, Ziffern, Punkt, Bindestrich, Unterstrich. So sehen dich andere.',
    'register.birth' => 'Geburtsdatum', 'register.birth_hint' => 'Du musst mindestens {age} Jahre alt sein. Andere sehen dein Geburtsdatum nicht.',
    'register.password' => 'Passwort', 'register.password_hint' => 'Mindestens 10 Zeichen.',
    'register.terms' => 'Ich akzeptiere die {terms} und habe die {privacy} gelesen.',
    'register.button' => 'Konto anlegen', 'register.closed' => 'Die Registrierung ist gerade geschlossen.',
    'register.error_email' => 'Bitte gib eine gültige E-Mail-Adresse ein.',
    'register.error_name' => 'Der Anzeigename passt nicht zu den Regeln.',
    'register.error_name_taken' => 'Dieser Anzeigename ist schon vergeben.',
    'register.error_age' => 'Für ElTouro musst du mindestens {age} Jahre alt sein.',
    'register.error_password' => 'Das Passwort ist zu kurz.',
    'register.error_terms' => 'Bitte bestätige die Nutzungsbedingungen.',
    'register.done' => 'Fast geschafft: Wir haben dir eine E-Mail geschickt. Klick auf den Link darin, um dein Konto zu aktivieren.',

    'verify.ok' => 'Deine E-Mail-Adresse ist bestätigt. Willkommen bei ElTouro!',
    'verify.error' => 'Dieser Link ist abgelaufen oder wurde schon benutzt.',

    'login.title' => 'Anmelden', 'login.button' => 'Anmelden', 'login.forgot' => 'Passwort vergessen?',
    'login.error' => 'E-Mail-Adresse oder Passwort stimmen nicht, oder das Konto ist noch nicht bestätigt.',
    'login.too_many' => 'Zu viele Versuche. Bitte warte ein paar Minuten.',
    'logout.ok' => 'Du bist abgemeldet.',

    'password.title' => 'Passwort vergessen', 'password.text' => 'Gib deine E-Mail-Adresse ein. Wenn es dazu ein Konto gibt, schicken wir dir einen Link zum Zurücksetzen.',
    'password.button' => 'Link schicken', 'password.sent' => 'Wenn es ein Konto mit dieser Adresse gibt, ist der Link unterwegs.',
    'password.new_title' => 'Neues Passwort', 'password.new_button' => 'Passwort speichern', 'password.new_ok' => 'Dein Passwort ist geändert. Du bist angemeldet.',

    'mail.verify_subject' => 'Bestätige dein ElTouro-Konto',
    'mail.verify_text' => "Hallo {name},\n\nbitte bestätige deine E-Mail-Adresse, um dein ElTouro-Konto zu aktivieren:\n\n{link}\n\nDer Link ist 48 Stunden gültig. Wenn du dich nicht registriert hast, ignoriere diese Mail.\n\nDein ElTouro-Team",
    'mail.reset_subject' => 'Dein ElTouro-Passwort zurücksetzen',
    'mail.reset_text' => "Hallo {name},\n\nhier kannst du ein neues Passwort festlegen:\n\n{link}\n\nDer Link ist 1 Stunde gültig. Wenn du das nicht angefordert hast, ignoriere diese Mail – dein Passwort bleibt unverändert.\n\nDein ElTouro-Team",

    'profile.title' => 'Dein Profil', 'profile.bio' => 'Über dich', 'profile.region' => 'Wo fährst du meistens?',
    'profile.language' => 'Sprache', 'profile.button' => 'Speichern', 'profile.saved' => 'Gespeichert.',

    'crews.title' => 'Herden', 'crews.search' => 'Herde oder Region suchen', 'crews.search_button' => 'Suchen',
    'crews.new' => 'Eigene Herde gründen', 'crews.none' => 'Keine Herden gefunden.',
    'crews.members' => '{n} Mitglieder', 'crews.mine' => 'Deine Herden', 'crews.discover' => 'Herden entdecken',

    'crew.name' => 'Name der Herde', 'crew.description' => 'Beschreibung', 'crew.region' => 'Region',
    'crew.visibility' => 'Sichtbarkeit', 'crew.listed' => 'Auffindbar – erscheint in der Suche', 'crew.secret' => 'Geheim – nur per Einladungslink zu finden',
    'crew.joining' => 'Beitritt', 'crew.open' => 'Offen – jeder kann direkt beitreten', 'crew.request' => 'Geschlossen – der Leitstier bestätigt Anfragen', 'crew.invite' => 'Nur mit Einladungslink',
    'crew.found' => 'Herde gründen', 'crew.founded' => 'Deine Herde ist gegründet. Du bist ihr Leitstier.',
    'crew.error_name' => 'Bitte gib einen Namen mit 3 bis 60 Zeichen ein.',
    'crew.join' => 'Beitreten', 'crew.request_join' => 'Beitritt anfragen', 'crew.leave' => 'Herde verlassen',
    'crew.joined' => 'Willkommen in der Herde!', 'crew.requested' => 'Deine Anfrage ist beim Leitstier.',
    'crew.request_pending' => 'Deine Anfrage wartet auf Bestätigung.', 'crew.left' => 'Du hast die Herde verlassen.',
    'crew.last_lead' => 'Du bist der einzige Leitstier. Ernenne erst jemand anderen, bevor du gehst.',
    'crew.invite_only' => 'Dieser Herde kannst du nur mit einem Einladungslink beitreten.',
    'crew.members_title' => 'Mitglieder', 'crew.members_only' => 'Die Mitgliederliste sehen nur Mitglieder.',
    'crew.lead' => 'Leitstier', 'crew.you' => 'du',
    'crew.requests_title' => 'Offene Anfragen', 'crew.accept' => 'Annehmen', 'crew.decline' => 'Ablehnen',
    'crew.remove' => 'Entfernen', 'crew.promote' => 'Zum Leitstier machen',
    'crew.invite_link' => 'Einladungslink', 'crew.invite_hint' => 'Wer diesen Link hat, kann die Herde sehen und beitreten.',
    'crew.invite_new' => 'Neuen Link erzeugen (alter wird ungültig)',
    'crew.settings' => 'Einstellungen der Herde', 'crew.save' => 'Speichern', 'crew.saved' => 'Gespeichert.',
    'crew.tours' => 'Touren der Herde', 'crew.tour_new' => 'Tour für diese Herde planen',

    'tours.title' => 'Touren', 'tours.mine' => 'Deine Touren', 'tours.crews' => 'Touren deiner Herden',
    'tours.public' => 'Öffentliche Touren', 'tours.none' => 'Hier ist noch nichts.',
    'tour.new' => 'Tour planen', 'tour.edit' => 'Tour bearbeiten', 'tour.save' => 'Tour speichern',
    'tour.saved' => 'Tour gespeichert.', 'tour.deleted' => 'Tour gelöscht.', 'tour.delete' => 'Tour löschen',
    'tour.name' => 'Name der Tour', 'tour.description' => 'Beschreibung', 'tour.crew' => 'Herde',
    'tour.difficulty' => 'Schwierigkeit', 'tour.difficulty_hint' => 'Deine Einschätzung für andere Fahrer.',
    'tour.d_easy' => 'Einfach', 'tour.d_moderate' => 'Mittel', 'tour.d_demanding' => 'Anspruchsvoll',
    'tour.style' => 'Fahrstil', 'tour.s_relaxed' => 'Gemütlich', 'tour.s_social' => 'Gesellig', 'tour.s_sporty' => 'Sportlich',
    'tour.rule_set' => 'Verkehrsregeln', 'tour.r_ekfv' => 'Aktuelle eKFV', 'tour.r_ekfv2027' => 'Ab 1. März 2027',
    'tour.visibility' => 'Wer sieht die Tour?', 'tour.v_private' => 'Nur ich', 'tour.v_group' => 'Meine Herde', 'tour.v_public' => 'Alle angemeldeten Fahrer',
    'tour.error_name' => 'Bitte gib der Tour einen Namen (mindestens 3 Zeichen).',
    'tour.error_route' => 'Die Route ist unvollständig. Setz mindestens zwei Punkte und warte, bis sie berechnet ist.',
    'tour.error_crew' => 'Für „Meine Herde“ wähle bitte eine Herde aus.',
    'tour.by' => 'von {name}', 'tour.start' => 'Start', 'tour.finish' => 'Ziel',
    'tour.length' => 'Länge', 'tour.ascent' => 'Anstieg',
    'tour.assessment' => 'Schwierigkeit und Fahrstil sind die Einschätzung des Erstellers.',
    'tour.freehand_warning' => '{p} % dieser Tour sind von Hand verbunden und nicht auf E-Scooter-Tauglichkeit geprüft (rot gestrichelt).',
    'tour.on_site' => 'Die Route ist ein Vorschlag. Vor Ort gelten immer die Verkehrszeichen.',
    'tour.gpx' => 'GPX herunterladen',

    'planner.instructions' => 'Klick in die Karte setzt einen Wegpunkt. Punkte lassen sich verschieben; ein Klick auf einen Punkt entfernt ihn.',
    'planner.undo' => 'Letzten Punkt entfernen', 'planner.loop' => 'Zurück zum Start', 'planner.locate' => 'Mein Standort', 'planner.clear' => 'Alle Punkte löschen',
    'planner.point' => 'Wegpunkt', 'planner.calculating' => 'Route wird berechnet …', 'planner.done' => 'Route berechnet.',
    'planner.error' => 'Die Route konnte gerade nicht berechnet werden. Versuch es gleich noch einmal.',
    'planner.notice_no_router' => 'Routing ist noch nicht angebunden – die Punkte werden gerade verbunden (Freihand).',
    'planner.notice_partly_freehand' => 'Ein Teil lässt sich nicht über erlaubte Wege führen und ist rot gestrichelt verbunden.',
    'planner.empty' => 'Setz mindestens zwei Punkte.', 'planner.stats' => '{km} km · {n} Wegpunkte', 'planner.freehand_share' => '{p} % freihand',
    'planner.locate_error' => 'Standort nicht verfügbar.',
    'planner.suggest_name' => '🎲 Namen würfeln',
    'planner.leg_too_long' => 'Zu weit: Zwischen zwei Punkten gehen höchstens {km} km Luftlinie – setz einen Punkt dazwischen.',
    'planner.loading_1' => 'Rindviecher werden gesattelt …',
    'planner.loading_2' => 'Akkus laden, Hörner polieren …',
    'planner.loading_3' => 'Der Leitstier schnuppert die Route …',
    'planner.loading_4' => 'Fußwege? Nicht mit uns. Suche Straßen …',
    'planner.loading_5' => 'Die Herde sammelt sich am Gatter …',
    'planner.loading_6' => 'Volt rein, Muh raus …',
    'planner.loading_7' => 'Rotes Tuch gesichtet – Kurs wird berechnet …',
    'planner.loading_8' => 'Weidezäune werden umfahren …',
    'planner.loading_9' => 'Staubwolke wird vorbereitet …',
    'planner.loading_10' => 'Kein Feldweg, kein Wald – nur Asphalt für Toros …',
    'tourname.any_1' => 'Stampede durch {place}',
    'tourname.any_2' => '{place} Rodeo',
    'tourname.any_3' => 'Hörner hoch, {place}!',
    'tourname.any_4' => 'Staubwolke über {place}',
    'tourname.any_5' => 'Volt-Ritt {place}',
    'tourname.any_6' => 'Herdenzug {place}',
    'tourname.any_7' => 'Rotes Tuch {place}',
    'tourname.any_8' => 'Corrida {place}',
    'tourname.any_9' => 'Asphalt-Toros {place}',
    'tourname.any_10' => 'Akku-Ausritt {place}',
    'tourname.loop_1' => 'Bullenrunde {place}',
    'tourname.loop_2' => 'Arena {place}',
    'tourname.loop_3' => 'Ehrenrunde {place}',
    'tourname.short_1' => 'Feierabend-Galopp {place}',
    'tourname.short_2' => 'Kurzer Galopp {place}',
    'tourname.long_1' => 'Akku-Marathon {place}',
    'tourname.long_2' => 'Langstrecken-Stampede {place}',
    'tourname.hilly_1' => 'Bergbullen {place}',
    'tourname.hilly_2' => 'Gipfelstiere {place}',
    'tourname.noplace_1' => 'Namenlose Stampede',
    'tourname.noplace_2' => 'Toro-Tour {km} km',
    'tourname.noplace_3' => '{km} km Staub & Volt',

    'forum.title' => 'Forum', 'forum.intro' => 'Austausch unter E-Scooter-Fahrern: Fragen, Tipps, Touren und Feedback zu ElTouro.',
    'forum.topics' => '{n} Themen', 'forum.replies' => '{n} Antworten', 'forum.by' => 'von {name}',
    'forum.new_topic' => 'Neues Thema', 'forum.no_topics' => 'Noch keine Themen. Fang an!',
    'forum.pinned' => 'Angepinnt', 'forum.locked' => 'Geschlossen', 'forum.locked_text' => 'Dieses Thema ist geschlossen.',
    'forum.subject' => 'Betreff', 'forum.text' => 'Dein Beitrag', 'forum.publish' => 'Veröffentlichen',
    'forum.reply_title' => 'Antworten', 'forum.send' => 'Antwort senden', 'forum.delete' => 'Löschen',
    'forum.deleted' => 'Dieser Beitrag wurde gelöscht.', 'forum.pages' => 'Seiten',
    'forum.format' => 'Absätze mit Leerzeile, **fett**, - Liste, [Link](https://…).',
    'forum.error_subject' => 'Der Betreff braucht mindestens 5 Zeichen.', 'forum.error_text' => 'Der Beitrag muss zwischen 2 und {max} Zeichen lang sein.',
    'forum.too_fast' => 'Nicht so schnell – warte ein paar Sekunden bis zum nächsten Beitrag.',
    'forum.m_pin' => 'Anpinnen', 'forum.m_unpin' => 'Nicht mehr anpinnen', 'forum.m_lock' => 'Schließen', 'forum.m_unlock' => 'Wieder öffnen', 'forum.m_delete' => 'Thema löschen',

    'report.link' => 'Melden', 'report.title' => 'Inhalt melden',
    'report.text' => 'Verstößt etwas gegen Gesetze oder unsere Nutzungsbedingungen? Beschreib kurz, was nicht in Ordnung ist. Wir prüfen jede Meldung.',
    'report.reason' => 'Was ist das Problem?', 'report.send' => 'Meldung abschicken',
    'report.error' => 'Bitte beschreib das Problem in mindestens 10 Zeichen.', 'report.thanks' => 'Danke, deine Meldung ist bei uns angekommen.',

    'talk.title' => 'Tränke', 'talk.open' => 'Zur Tränke',
    'talk.intro' => 'Hier trifft sich eure Herde: Absprachen, Fragen, Foto-Links, Geschichten von der letzten Tour. Nur Mitglieder sehen, was hier steht.',
    'talk.members_only' => 'Die Tränke ist nur für Mitglieder dieser Herde.',
    'talk.new_topic' => 'Neues Thema', 'talk.empty' => 'Noch still an der Tränke. Mach den Anfang!',
    'talk.error_subject' => 'Der Betreff braucht mindestens 3 Zeichen.',
    'talk.new' => 'neu', 'talk.n_new' => '{n} neu', 'talk.posts' => '{n} Beiträge',
    'talk.unread_since' => 'Neu seit deinem letzten Besuch', 'talk.edited' => 'bearbeitet',
    'talk.deleted' => 'Beitrag gelöscht', 'talk.like' => 'Gefällt mir', 'talk.reply' => 'Antworten', 'talk.delete' => 'Löschen',
    'talk.placeholder' => 'Schreib etwas an die Herde …', 'talk.send_hint' => 'Strg + Enter zum Senden',
    'talk.reply_clear' => 'Antwort-Bezug entfernen',
    'talk.js_new_posts' => '{n} neue Beiträge – anzeigen', 'talk.js_reply_to' => 'Antwort an {name}',
    'talk.js_delete_confirm' => 'Diesen Beitrag wirklich löschen?', 'talk.js_error' => 'Das hat nicht geklappt. Bitte versuch es noch einmal.',
    'talk.js_loading' => 'Lädt …', 'talk.js_no_more' => 'Das war alles.',

    'time.now' => 'gerade eben', 'time.min' => 'vor {n} Min.', 'time.hours' => 'vor {n} Std.', 'time.days' => 'vor {n} Tagen',
    'footer.imprint' => 'Impressum', 'footer.privacy' => 'Datenschutz', 'footer.terms' => 'Nutzungsbedingungen',
    'page.empty' => 'Diese Seite wird gerade vorbereitet.',

    'join.kicker' => 'Einladung', 'join.title' => '{name} lädt dich zu ElTouro ein',
    'join.register' => 'Mit E-Mail-Adresse registrieren', 'join.have_account' => 'Schon dabei?',
    'invite.title' => 'Lade Fahrer zu ElTouro ein', 'invite.text' => 'Dein persönlicher Einladungslink. Wer darüber zu ElTouro kommt, wird dir zugeordnet – das zählt später für Rang und Abzeichen.',
    'invite.share_title' => 'Komm zu ElTouro', 'invite.share_text' => '{name} lädt dich zu ElTouro ein – Touren für den E-Scooter planen und gemeinsam fahren.',
    'invite.count' => 'Über deine Links sind schon {n} Fahrer zu ElTouro gekommen.', 'invite.none' => 'Über deine Links ist noch niemand dazugekommen.',
    'invite.came_via' => 'Du bist über {name} zu ElTouro gekommen.',

    'google.button' => 'Mit Google anmelden', 'google.button_register' => 'Mit Google registrieren', 'google.or' => 'oder mit E-Mail-Adresse',
    'google.cancelled' => 'Die Anmeldung mit Google wurde abgebrochen.',
    'google.error' => 'Die Anmeldung mit Google hat nicht geklappt. Bitte versuch es noch einmal.',
    'google.blocked' => 'Dieses Konto ist gesperrt.',
    'google.linked_now' => 'Dein Google-Konto ist jetzt mit deinem ElTouro-Konto verbunden.',
    'google.complete_title' => 'Fast geschafft',
    'google.complete_text' => 'Google hat deine Adresse {email} bestätigt. Jetzt noch dein Anzeigename und dein Geburtsdatum – dann bist du dabei.',
    'google.connected' => 'Mit Google verbunden ({email}).',

    'share.title' => 'Tour teilen', 'share.create' => 'Link zum Teilen erstellen', 'share.link' => 'Link zur Tour',
    'share.what_is_visible' => 'Wer den Link hat, sieht ohne Anmeldung: Name, Länge, Anstieg, Schwierigkeit, Fahrstil und die Strecke ohne die ersten und letzten {m} m. Wer die Tour erstellt hat, die Herde und die Beschreibung bleiben verborgen.',
    'share.private_hint' => 'Auch wenn die Tour sonst nicht öffentlich ist: Über den Link kann sie jeder sehen, bis du ihn deaktivierst.',
    'share.copy' => 'Link kopieren', 'share.copied' => 'Kopiert!', 'share.native' => 'Teilen …', 'share.preview' => 'Vorschau ansehen',
    'share.revoke' => 'Link deaktivieren', 'share.created' => 'Der Link zum Teilen ist bereit.', 'share.revoked' => 'Der Link ist deaktiviert und funktioniert nicht mehr.',
    'share.gone' => 'Diese Tour wird nicht mehr geteilt.',
    'share.kicker' => 'E-Scooter-Tour auf ElTouro', 'share.meta_description' => 'E-Scooter-Tour: {summary}. Plane deine Tour und finde deine Herde auf ElTouro.',
    'share.image_alt' => 'Verlauf der Strecke', 'share.privacy_note' => 'Anfang und Ende der Strecke ({m} m) sind zum Schutz des Erstellers ausgeblendet.',
    'share.open_tour' => 'Tour in ElTouro öffnen', 'share.discover' => 'Weitere Touren entdecken',
    'share.cta_text' => 'Auf ElTouro planst du Touren für den E-Scooter, findest deine Herde und verabredest dich zu Ausfahrten.',
    'share.report' => 'Inhalt melden', 'share.report_subject' => 'Meldung zu geteilter Tour',

    'nav.rides' => 'Ausfahrten',
    'home.my_rides' => 'Deine nächsten Ausfahrten', 'home.all_rides' => 'Alle Ausfahrten', 'home.no_rides' => 'Du bist für keine Ausfahrt angemeldet.',
    'crew.rides' => 'Ausfahrten der Herde', 'crew.no_rides' => 'Gerade ist keine Ausfahrt geplant. Biete doch eine an!',
    'tour.rides' => 'Ausfahrten auf dieser Tour', 'tour.no_rides' => 'Für diese Tour ist keine Ausfahrt geplant.',
    'tour.offer_ride' => 'Als Ausfahrt anbieten', 'tour.private_no_ride' => 'Eine private Tour kannst du nicht als Ausfahrt anbieten. Stell sie dafür auf „Meine Herde“ oder „Alle angemeldeten Fahrer“.',
    'tour.delete_has_rides' => 'Auf dieser Tour ist noch eine Ausfahrt geplant. Sag sie zuerst ab, dann kannst du die Tour löschen.',

    'rides.title' => 'Ausfahrten', 'rides.intro' => 'Gemeinsam fahren: Termin, Treffpunkt, Anmeldung. Jede Ausfahrt organisiert ein Fahrer aus der Community – ElTouro vermittelt nur.',
    'rides.mine' => 'Deine Ausfahrten', 'rides.upcoming' => 'Kommende Ausfahrten', 'rides.past' => 'Vergangene Ausfahrten',
    'rides.none_mine' => 'Du hast dich noch für keine Ausfahrt angemeldet.', 'rides.none' => 'Gerade ist nichts geplant.',

    'ride.new' => 'Ausfahrt anbieten', 'ride.edit' => 'Ausfahrt bearbeiten', 'ride.by' => 'organisiert von {name}',
    'ride.v_public' => 'offen für alle angemeldeten Fahrer', 'ride.v_group' => 'für die Herde {name}',
    'ride.cancelled' => 'Abgesagt', 'ride.free_places' => '{n} Plätze frei', 'ride.full' => 'Ausgebucht',
    'ride.you_confirmed_short' => 'Du bist dabei', 'ride.you_waitlist_short' => 'Du stehst auf der Warteliste',
    'ride.not_editable' => 'Diese Ausfahrt lässt sich nicht mehr ändern.',
    'ride.pick_tour_text' => 'Welche Tour fahrt ihr? Hier stehen öffentliche Touren und die Touren deiner Herden. Private Touren erscheinen nicht – stell sie vorher auf „Meine Herde“ oder „Alle“.',
    'ride.no_tours' => 'Es gibt noch keine Tour, die du als Ausfahrt anbieten kannst. Plan zuerst eine Tour.',
    'ride.tour' => 'Tour', 'ride.continue' => 'Weiter', 'ride.other_tour' => 'andere Tour wählen',
    'ride.map_hint' => 'Klick in die Karte, um den Treffpunkt zu markieren. Den Pin kannst du verschieben.',
    'ride.meeting_at_start' => 'Treffpunkt = Start der Tour', 'ride.meeting_clear' => 'Pin entfernen',
    'ride.meeting_point' => 'Treffpunkt', 'ride.meeting_hint' => 'So, dass man euch findet: z. B. „Parkplatz am Rheinufer, beim Kiosk“.',
    'ride.title_label' => 'Titel der Ausfahrt', 'ride.date' => 'Datum', 'ride.time' => 'Uhrzeit (Treffen)',
    'ride.capacity' => 'Teilnehmergrenze', 'ride.capacity_hint' => 'Inklusive dir. Pflichtangabe – lieber klein anfangen.',
    'ride.waitlist_enabled' => 'Warteliste, wenn alle Plätze vergeben sind',
    'ride.audience' => 'Für wen?', 'ride.audience_crew' => 'Herde: {name}', 'ride.audience_public' => 'Alle angemeldeten Fahrer (öffentlich)',
    'ride.audience_hint' => 'Ausfahrten einer Herde erscheinen auf der Herdenseite und mit eigenem Thema in der Tränke.',
    'ride.description' => 'Beschreibung', 'ride.description_hint' => 'Pausen, Ziel, was man mitbringen sollte. Absätze mit Leerzeile, **fett**, - Liste.',
    'ride.stvo29_confirm' => 'Ab {n} Teilnehmern: Ich habe geprüft, ob für diese Ausfahrt eine Erlaubnis der Straßenverkehrsbehörde nach § 29 StVO nötig ist, und kümmere mich darum.',
    'ride.road_legal_organizer' => 'Ich fahre selbst mit einem zugelassenen und versicherten E-Scooter und nehme nur Fahrer mit, die das auch tun.',
    'ride.photo_consent' => 'Fotos und Videos von mir bei dieser Ausfahrt sind okay und dürfen mit den Teilnehmern und in der Herde geteilt werden. (freiwillig, jederzeit änderbar)',
    'ride.organizer_note' => 'Du bist der Organisator: Du bist automatisch angemeldet und sagst die Ausfahrt über ElTouro ab, falls sie nicht stattfindet. ElTouro veranstaltet die Fahrt nicht.',
    'ride.save' => 'Speichern', 'ride.publish' => 'Ausfahrt veröffentlichen',
    'ride.error_title' => 'Bitte gib der Ausfahrt einen Titel (mindestens 3 Zeichen).',
    'ride.error_date' => 'Bitte gib ein gültiges Datum und eine Uhrzeit an.',
    'ride.error_date_range' => 'Der Termin muss in der Zukunft und höchstens ein Jahr entfernt liegen.',
    'ride.error_meeting' => 'Bitte beschreib den Treffpunkt.',
    'ride.error_capacity' => 'Die Teilnehmergrenze muss zwischen {min} und {max} liegen.',
    'ride.error_capacity_below' => 'Es sind schon {n} Fahrer angemeldet – die Grenze kann nicht darunter liegen.',
    'ride.error_stvo29' => 'Ab {n} Teilnehmern musst du bestätigen, dass du die Erlaubnispflicht nach § 29 StVO geprüft hast.',
    'ride.error_audience' => 'Bitte wähle eine deiner Herden oder „öffentlich“.',
    'ride.error_tour_visibility' => 'Diese Tour können nicht alle Teilnehmer sehen. Für eine öffentliche Ausfahrt muss die Tour öffentlich sein, für eine Herde öffentlich oder dieser Herde zugeordnet.',
    'ride.error_road_legal' => 'Ohne zugelassenen und versicherten E-Scooter geht es nicht – bitte bestätige das.',
    'ride.error_cancel_reason' => 'Bitte gib kurz einen Grund für die Absage an.',
    'ride.saved' => 'Gespeichert.', 'ride.saved_notified' => 'Gespeichert. Die Angemeldeten bekommen eine E-Mail mit der Änderung.',
    'ride.created' => 'Deine Ausfahrt ist veröffentlicht.',
    'ride.talk_title' => 'Ausfahrt: {title} ({date})',
    'ride.talk_announcement' => "**{when}**\nTreffpunkt: {meeting}\nTour: {tour} ({km})\nPlätze: {capacity}\n\n[Zur Ausfahrt und Anmeldung]({link})",
    'ride.talk_changed' => "**Geändert:** Die Ausfahrt ist jetzt am {when}, Treffpunkt: {meeting}.",
    'ride.talk_cancelled' => "**Abgesagt:** {reason}",
    'ride.signup_confirmed' => 'Du bist dabei! Wir sehen uns am Treffpunkt.', 'ride.signup_waitlist' => 'Du stehst auf der Warteliste. Wird ein Platz frei, rückst du automatisch nach und bekommst eine E-Mail.',
    'ride.signup_full' => 'Leider ist die Ausfahrt ausgebucht.', 'ride.signup_closed' => 'Für diese Ausfahrt kann man sich nicht mehr anmelden.',
    'ride.signup_already' => 'Du bist schon angemeldet.', 'ride.withdrawn' => 'Du bist abgemeldet.', 'ride.photo_saved' => 'Deine Entscheidung zu Fotos ist gespeichert.',
    'ride.cancelled_ok' => 'Die Ausfahrt ist abgesagt. Alle Angemeldeten bekommen eine E-Mail.',
    'ride.is_cancelled' => 'Diese Ausfahrt wurde abgesagt: {reason}', 'ride.is_past' => 'Diese Ausfahrt hat schon stattgefunden.',
    'ride.places' => 'Plätze', 'ride.free_of' => '{n} von {max} frei', 'ride.waitlist_count' => '{n} auf der Warteliste',
    'ride.to_tour' => 'Zur Tour', 'ride.to_talk' => 'In der Tränke besprechen', 'ride.to_ride' => 'Zur Ausfahrt',
    'ride.tour_gone' => 'Die Tour zu dieser Ausfahrt wurde gelöscht.',
    'ride.rule_organizer' => 'Diese Ausfahrt organisiert {name}, nicht ElTouro.',
    'ride.rule_road_legal' => 'Mitfahren nur mit zugelassenem und versichertem E-Scooter.',
    'ride.rule_own_risk' => 'Jeder fährt auf eigene Verantwortung. Schwierigkeit und Fahrstil sind die Einschätzung des Organisators.',
    'ride.rule_signs' => 'Die Route ist ein Vorschlag – vor Ort gelten immer die Verkehrszeichen und die StVO.',
    'ride.rule_stvo29' => 'Der Organisator hat bestätigt, die Erlaubnispflicht nach § 29 StVO für diese Gruppengröße geprüft zu haben.',
    'ride.you_organize' => 'Du organisierst diese Ausfahrt.', 'ride.you_confirmed' => 'Du bist angemeldet.', 'ride.you_waitlist' => 'Du stehst auf Platz {n} der Warteliste.',
    'ride.photo_save' => 'Speichern', 'ride.withdraw' => 'Abmelden',
    'ride.signup_title' => 'Mitfahren', 'ride.waitlist_title' => 'Ausgebucht – auf die Warteliste',
    'ride.full_no_waitlist' => 'Alle Plätze sind vergeben, eine Warteliste gibt es nicht.',
    'ride.road_legal_rider' => 'Ich fahre mit einem zugelassenen und versicherten E-Scooter.',
    'ride.photo_hint' => 'Auch ohne Häkchen kannst du mitfahren. Die anderen sehen dann bei deinem Namen „keine Fotos“.',
    'ride.signup' => 'Anmelden', 'ride.join_waitlist' => 'Auf die Warteliste',
    'ride.participants' => 'Wer fährt mit?', 'ride.participants_hidden' => '{n} Fahrer sind angemeldet. Die Namen sehen nur Teilnehmer.',
    'ride.organizer' => 'Organisator', 'ride.on_waitlist' => 'Warteliste', 'ride.no_photo' => 'keine Fotos', 'ride.no_photo_title' => 'Bitte nicht fotografieren oder filmen',
    'ride.cancel_title' => 'Ausfahrt absagen', 'ride.cancel_text' => 'Alle Angemeldeten und die Warteliste bekommen eine E-Mail mit deinem Grund.',
    'ride.cancel_reason' => 'Grund', 'ride.cancel_button' => 'Ausfahrt absagen',

    'mail.ride_promoted_subject' => 'Du bist dabei: {title}',
    'mail.ride_promoted_text' => "Hallo {name},\n\nein Platz ist frei geworden – du bist von der Warteliste nachgerückt und jetzt angemeldet für:\n\n{title}\n{when}\nTreffpunkt: {meeting}\n\n{link}\n\nWenn du doch nicht kannst, melde dich bitte dort wieder ab, damit der Nächste nachrückt.\n\nDein ElTouro-Team",
    'mail.ride_changed_subject' => 'Geändert: {title}',
    'mail.ride_changed_text' => "Hallo {name},\n\nbei deiner Ausfahrt hat sich etwas geändert:\n\n{title}\n{when}\nTreffpunkt: {meeting}\n\n{link}\n\nPasst es nicht mehr? Dann melde dich bitte dort ab.\n\nDein ElTouro-Team",
    'mail.ride_cancelled_subject' => 'Abgesagt: {title}',
    'mail.ride_cancelled_text' => "Hallo {name},\n\ndie Ausfahrt „{title}“ am {when} wurde abgesagt.\n\nGrund: {reason}\n\n{link}\n\nDein ElTouro-Team",
],
'en' => [
    'nav.skip' => 'Skip to content', 'nav.main' => 'Main navigation', 'nav.language' => 'Language',
    'nav.crews' => 'Crews', 'nav.profile' => 'Profile', 'nav.admin' => 'Admin',
    'nav.login' => 'Log in', 'nav.logout' => 'Log out', 'nav.register' => 'Sign up',
    'nav.tours' => 'Routes', 'nav.forum' => 'Forum',
    'env.notice' => 'Preview version, data may be reset at any time',

    'error.csrf' => 'Your session expired. Please reload the page and try again.',
    'error.general' => 'That didn’t work just now. Please try again.',
    'error.not_found' => 'Not found.',

    'access.title' => 'Preview access', 'access.text' => 'ElTouro is still in development here. Enter the tester password to get in.',
    'access.password' => 'Tester password', 'access.button' => 'Let me in', 'access.wrong' => 'Wrong password.',

    'home.title' => 'Home', 'home.hello' => 'Hi {name}!',
    'home.my_crews' => 'Your crews', 'home.no_crews' => 'You’re not in a crew yet. Look around or start your own.',
    'home.guest_title' => 'Find your ride. Find your crew.',
    'home.guest_text' => 'Log in to find crews and ride out together.',

    'register.title' => 'Sign up', 'register.email' => 'Email address', 'register.name' => 'Display name',
    'register.name_hint' => '3 to 30 characters: letters, digits, dot, hyphen, underscore. This is how others see you.',
    'register.birth' => 'Date of birth', 'register.birth_hint' => 'You must be at least {age} years old. Others can’t see your date of birth.',
    'register.password' => 'Password', 'register.password_hint' => 'At least 10 characters.',
    'register.terms' => 'I accept the {terms} and have read the {privacy}.',
    'register.button' => 'Create account', 'register.closed' => 'Sign-up is currently closed.',
    'register.error_email' => 'Please enter a valid email address.',
    'register.error_name' => 'The display name doesn’t match the rules.',
    'register.error_name_taken' => 'This display name is already taken.',
    'register.error_age' => 'You must be at least {age} years old to use ElTouro.',
    'register.error_password' => 'The password is too short.',
    'register.error_terms' => 'Please accept the terms of use.',
    'register.done' => 'Almost there: we’ve sent you an email. Click the link inside to activate your account.',

    'verify.ok' => 'Your email address is confirmed. Welcome to ElTouro!',
    'verify.error' => 'This link has expired or was already used.',

    'login.title' => 'Log in', 'login.button' => 'Log in', 'login.forgot' => 'Forgot your password?',
    'login.error' => 'Email or password is wrong, or the account isn’t confirmed yet.',
    'login.too_many' => 'Too many attempts. Please wait a few minutes.',
    'logout.ok' => 'You’re logged out.',

    'password.title' => 'Forgot password', 'password.text' => 'Enter your email address. If there’s an account for it, we’ll send you a reset link.',
    'password.button' => 'Send link', 'password.sent' => 'If there’s an account with this address, the link is on its way.',
    'password.new_title' => 'New password', 'password.new_button' => 'Save password', 'password.new_ok' => 'Your password has been changed. You’re logged in.',

    'mail.verify_subject' => 'Confirm your ElTouro account',
    'mail.verify_text' => "Hi {name},\n\nplease confirm your email address to activate your ElTouro account:\n\n{link}\n\nThe link is valid for 48 hours. If you didn’t sign up, just ignore this email.\n\nThe ElTouro team",
    'mail.reset_subject' => 'Reset your ElTouro password',
    'mail.reset_text' => "Hi {name},\n\nyou can set a new password here:\n\n{link}\n\nThe link is valid for 1 hour. If you didn’t request this, ignore this email – your password stays the same.\n\nThe ElTouro team",

    'profile.title' => 'Your profile', 'profile.bio' => 'About you', 'profile.region' => 'Where do you usually ride?',
    'profile.language' => 'Language', 'profile.button' => 'Save', 'profile.saved' => 'Saved.',

    'crews.title' => 'Crews', 'crews.search' => 'Search crew or area', 'crews.search_button' => 'Search',
    'crews.new' => 'Start your own crew', 'crews.none' => 'No crews found.',
    'crews.members' => '{n} members', 'crews.mine' => 'Your crews', 'crews.discover' => 'Discover crews',

    'crew.name' => 'Crew name', 'crew.description' => 'Description', 'crew.region' => 'Area',
    'crew.visibility' => 'Visibility', 'crew.listed' => 'Listed – shows up in search', 'crew.secret' => 'Secret – only findable via invite link',
    'crew.joining' => 'Joining', 'crew.open' => 'Open – anyone can join right away', 'crew.request' => 'Closed – the crew lead approves requests', 'crew.invite' => 'Invite link only',
    'crew.found' => 'Start crew', 'crew.founded' => 'Your crew is live. You’re its crew lead.',
    'crew.error_name' => 'Please enter a name with 3 to 60 characters.',
    'crew.join' => 'Join', 'crew.request_join' => 'Request to join', 'crew.leave' => 'Leave crew',
    'crew.joined' => 'Welcome to the crew!', 'crew.requested' => 'Your request is with the crew lead.',
    'crew.request_pending' => 'Your request is waiting for approval.', 'crew.left' => 'You left the crew.',
    'crew.last_lead' => 'You’re the only crew lead. Make someone else crew lead before you leave.',
    'crew.invite_only' => 'You can only join this crew with an invite link.',
    'crew.members_title' => 'Members', 'crew.members_only' => 'Only members can see the member list.',
    'crew.lead' => 'Crew lead', 'crew.you' => 'you',
    'crew.requests_title' => 'Open requests', 'crew.accept' => 'Accept', 'crew.decline' => 'Decline',
    'crew.remove' => 'Remove', 'crew.promote' => 'Make crew lead',
    'crew.invite_link' => 'Invite link', 'crew.invite_hint' => 'Anyone with this link can see and join the crew.',
    'crew.invite_new' => 'Create new link (old one stops working)',
    'crew.settings' => 'Crew settings', 'crew.save' => 'Save', 'crew.saved' => 'Saved.',
    'crew.tours' => 'Crew routes', 'crew.tour_new' => 'Plan a route for this crew',

    'tours.title' => 'Routes', 'tours.mine' => 'Your routes', 'tours.crews' => 'Routes from your crews',
    'tours.public' => 'Public routes', 'tours.none' => 'Nothing here yet.',
    'tour.new' => 'Plan a route', 'tour.edit' => 'Edit route', 'tour.save' => 'Save route',
    'tour.saved' => 'Route saved.', 'tour.deleted' => 'Route deleted.', 'tour.delete' => 'Delete route',
    'tour.name' => 'Route name', 'tour.description' => 'Description', 'tour.crew' => 'Crew',
    'tour.difficulty' => 'Difficulty', 'tour.difficulty_hint' => 'Your assessment for other riders.',
    'tour.d_easy' => 'Easy', 'tour.d_moderate' => 'Moderate', 'tour.d_demanding' => 'Demanding',
    'tour.style' => 'Riding style', 'tour.s_relaxed' => 'Relaxed', 'tour.s_social' => 'Social', 'tour.s_sporty' => 'Sporty',
    'tour.rule_set' => 'Traffic rules', 'tour.r_ekfv' => 'Current German rules (eKFV)', 'tour.r_ekfv2027' => 'From 1 March 2027',
    'tour.visibility' => 'Who can see it?', 'tour.v_private' => 'Only me', 'tour.v_group' => 'My crew', 'tour.v_public' => 'All logged-in riders',
    'tour.error_name' => 'Please give the route a name (at least 3 characters).',
    'tour.error_route' => 'The route is incomplete. Set at least two points and wait until it’s calculated.',
    'tour.error_crew' => 'For “My crew”, please choose a crew.',
    'tour.by' => 'by {name}', 'tour.start' => 'Start', 'tour.finish' => 'Finish',
    'tour.length' => 'Length', 'tour.ascent' => 'Climb',
    'tour.assessment' => 'Difficulty and riding style are the creator’s own assessment.',
    'tour.freehand_warning' => '{p}% of this route is connected by hand and not checked for e-scooter suitability (red dashes).',
    'tour.on_site' => 'The route is a suggestion. Road signs on site always take priority.',
    'tour.gpx' => 'Download GPX',

    'planner.instructions' => 'Click the map to add a waypoint. Drag points to move them; click a point to remove it.',
    'planner.undo' => 'Remove last point', 'planner.loop' => 'Back to start', 'planner.locate' => 'My location', 'planner.clear' => 'Clear all points',
    'planner.point' => 'Waypoint', 'planner.calculating' => 'Calculating route …', 'planner.done' => 'Route calculated.',
    'planner.error' => 'The route couldn’t be calculated just now. Please try again in a moment.',
    'planner.notice_no_router' => 'Routing isn’t connected yet – points are joined with straight lines (freehand).',
    'planner.notice_partly_freehand' => 'Part of the route can’t follow permitted paths and is joined with red dashes.',
    'planner.empty' => 'Set at least two points.', 'planner.stats' => '{km} km · {n} waypoints', 'planner.freehand_share' => '{p}% freehand',
    'planner.locate_error' => 'Location not available.',
    'planner.suggest_name' => '🎲 Roll a name',
    'planner.leg_too_long' => 'Too far: at most {km} km in a straight line between two points – add a point in between.',
    'planner.loading_1' => 'Saddling up the cattle …',
    'planner.loading_2' => 'Charging batteries, polishing horns …',
    'planner.loading_3' => 'The crew lead is sniffing out the route …',
    'planner.loading_4' => 'Footpaths? Not for us. Finding roads …',
    'planner.loading_5' => 'The herd gathers at the gate …',
    'planner.loading_6' => 'Volts in, moos out …',
    'planner.loading_7' => 'Red cape spotted – plotting a course …',
    'planner.loading_8' => 'Steering around the pasture fences …',
    'planner.loading_9' => 'Preparing the dust cloud …',
    'planner.loading_10' => 'No dirt tracks, no forest – only asphalt for toros …',
    'tourname.any_1' => 'Stampede through {place}',
    'tourname.any_2' => '{place} Rodeo',
    'tourname.any_3' => 'Horns up, {place}!',
    'tourname.any_4' => 'Dust over {place}',
    'tourname.any_5' => 'Volt Ride {place}',
    'tourname.any_6' => 'Herd Run {place}',
    'tourname.any_7' => 'Red Cape {place}',
    'tourname.any_8' => 'Corrida {place}',
    'tourname.any_9' => 'Asphalt Toros {place}',
    'tourname.any_10' => 'Battery Ride {place}',
    'tourname.loop_1' => 'Bull Loop {place}',
    'tourname.loop_2' => 'Arena {place}',
    'tourname.loop_3' => 'Victory Lap {place}',
    'tourname.short_1' => 'After-Work Gallop {place}',
    'tourname.short_2' => 'Quick Gallop {place}',
    'tourname.long_1' => 'Battery Marathon {place}',
    'tourname.long_2' => 'Long-Haul Stampede {place}',
    'tourname.hilly_1' => 'Mountain Bulls {place}',
    'tourname.hilly_2' => 'Summit Toros {place}',
    'tourname.noplace_1' => 'Nameless Stampede',
    'tourname.noplace_2' => 'Toro Tour {km} km',
    'tourname.noplace_3' => '{km} km of Dust & Volts',

    'forum.title' => 'Forum', 'forum.intro' => 'Talk with other e-scooter riders: questions, tips, rides and feedback on ElTouro.',
    'forum.topics' => '{n} topics', 'forum.replies' => '{n} replies', 'forum.by' => 'by {name}',
    'forum.new_topic' => 'New topic', 'forum.no_topics' => 'No topics yet. Start one!',
    'forum.pinned' => 'Pinned', 'forum.locked' => 'Closed', 'forum.locked_text' => 'This topic is closed.',
    'forum.subject' => 'Subject', 'forum.text' => 'Your post', 'forum.publish' => 'Publish',
    'forum.reply_title' => 'Reply', 'forum.send' => 'Send reply', 'forum.delete' => 'Delete',
    'forum.deleted' => 'This post was deleted.', 'forum.pages' => 'Pages',
    'forum.format' => 'Blank line for paragraphs, **bold**, - list, [link](https://…).',
    'forum.error_subject' => 'The subject needs at least 5 characters.', 'forum.error_text' => 'Posts must be between 2 and {max} characters.',
    'forum.too_fast' => 'Not so fast – wait a few seconds before your next post.',
    'forum.m_pin' => 'Pin', 'forum.m_unpin' => 'Unpin', 'forum.m_lock' => 'Close', 'forum.m_unlock' => 'Reopen', 'forum.m_delete' => 'Delete topic',

    'report.link' => 'Report', 'report.title' => 'Report content',
    'report.text' => 'Does something break the law or our terms of use? Briefly describe what’s wrong. We review every report.',
    'report.reason' => 'What’s the problem?', 'report.send' => 'Send report',
    'report.error' => 'Please describe the problem in at least 10 characters.', 'report.thanks' => 'Thanks, we’ve received your report.',

    'talk.title' => 'Crew talk', 'talk.open' => 'Open crew talk',
    'talk.intro' => 'Where your crew hangs out: plans, questions, photo links, stories from the last ride. Only members can see what’s here.',
    'talk.members_only' => 'Crew talk is only for members of this crew.',
    'talk.new_topic' => 'New topic', 'talk.empty' => 'All quiet so far. Start the conversation!',
    'talk.error_subject' => 'The subject needs at least 3 characters.',
    'talk.new' => 'new', 'talk.n_new' => '{n} new', 'talk.posts' => '{n} posts',
    'talk.unread_since' => 'New since your last visit', 'talk.edited' => 'edited',
    'talk.deleted' => 'Post deleted', 'talk.like' => 'Like', 'talk.reply' => 'Reply', 'talk.delete' => 'Delete',
    'talk.placeholder' => 'Write something to your crew …', 'talk.send_hint' => 'Ctrl + Enter to send',
    'talk.reply_clear' => 'Remove reply reference',
    'talk.js_new_posts' => '{n} new posts – show', 'talk.js_reply_to' => 'Replying to {name}',
    'talk.js_delete_confirm' => 'Really delete this post?', 'talk.js_error' => 'That didn’t work. Please try again.',
    'talk.js_loading' => 'Loading …', 'talk.js_no_more' => 'That’s everything.',

    'time.now' => 'just now', 'time.min' => '{n} min ago', 'time.hours' => '{n} h ago', 'time.days' => '{n} days ago',
    'footer.imprint' => 'Legal notice', 'footer.privacy' => 'Privacy', 'footer.terms' => 'Terms of use',
    'page.empty' => 'This page is being prepared.',

    'join.kicker' => 'Invitation', 'join.title' => '{name} invites you to ElTouro',
    'join.register' => 'Sign up with email', 'join.have_account' => 'Already riding with us?',
    'invite.title' => 'Invite riders to ElTouro', 'invite.text' => 'Your personal invite link. Whoever joins ElTouro through it is credited to you – this will count towards rank and badges.',
    'invite.share_title' => 'Join ElTouro', 'invite.share_text' => '{name} invites you to ElTouro – plan e-scooter routes and ride together.',
    'invite.count' => '{n} riders have already joined ElTouro through your links.', 'invite.none' => 'Nobody has joined through your links yet.',
    'invite.came_via' => 'You joined ElTouro through {name}.',

    'google.button' => 'Sign in with Google', 'google.button_register' => 'Sign up with Google', 'google.or' => 'or with your email address',
    'google.cancelled' => 'Signing in with Google was cancelled.',
    'google.error' => 'Signing in with Google didn’t work. Please try again.',
    'google.blocked' => 'This account is blocked.',
    'google.linked_now' => 'Your Google account is now connected to your ElTouro account.',
    'google.complete_title' => 'Almost there',
    'google.complete_text' => 'Google has confirmed your address {email}. Just add your display name and date of birth and you’re in.',
    'google.connected' => 'Connected with Google ({email}).',

    'share.title' => 'Share route', 'share.create' => 'Create share link', 'share.link' => 'Link to the route',
    'share.what_is_visible' => 'Anyone with the link sees, without logging in: name, length, climb, difficulty, riding style and the track without its first and last {m} m. Who created it, the crew and the description stay hidden.',
    'share.private_hint' => 'Even if the route is otherwise not public: anyone with the link can see it until you deactivate the link.',
    'share.copy' => 'Copy link', 'share.copied' => 'Copied!', 'share.native' => 'Share …', 'share.preview' => 'View preview',
    'share.revoke' => 'Deactivate link', 'share.created' => 'Your share link is ready.', 'share.revoked' => 'The link is deactivated and no longer works.',
    'share.gone' => 'This route is no longer shared.',
    'share.kicker' => 'E-scooter route on ElTouro', 'share.meta_description' => 'E-scooter route: {summary}. Plan your ride and find your crew on ElTouro.',
    'share.image_alt' => 'Shape of the route', 'share.privacy_note' => 'Start and end of the track ({m} m) are hidden to protect the creator.',
    'share.open_tour' => 'Open route in ElTouro', 'share.discover' => 'Discover more routes',
    'share.cta_text' => 'On ElTouro you plan e-scooter routes, find your crew and meet up for rides.',
    'share.report' => 'Report content', 'share.report_subject' => 'Report about a shared route',

    'nav.rides' => 'Rides',
    'home.my_rides' => 'Your next rides', 'home.all_rides' => 'All rides', 'home.no_rides' => 'You haven’t signed up for any ride.',
    'crew.rides' => 'Crew rides', 'crew.no_rides' => 'No ride planned right now. Why not offer one?',
    'tour.rides' => 'Rides on this route', 'tour.no_rides' => 'No ride is planned for this route.',
    'tour.offer_ride' => 'Offer as a ride', 'tour.private_no_ride' => 'You can’t offer a private route as a ride. Set it to “My crew” or “All logged-in riders” first.',
    'tour.delete_has_rides' => 'A ride is still planned on this route. Cancel it first, then you can delete the route.',

    'rides.title' => 'Rides', 'rides.intro' => 'Ride together: date, meeting point, sign-up. Every ride is organised by a rider from the community – ElTouro only connects you.',
    'rides.mine' => 'Your rides', 'rides.upcoming' => 'Upcoming rides', 'rides.past' => 'Past rides',
    'rides.none_mine' => 'You haven’t signed up for a ride yet.', 'rides.none' => 'Nothing planned right now.',

    'ride.new' => 'Offer a ride', 'ride.edit' => 'Edit ride', 'ride.by' => 'organised by {name}',
    'ride.v_public' => 'open to all logged-in riders', 'ride.v_group' => 'for the crew {name}',
    'ride.cancelled' => 'Cancelled', 'ride.free_places' => '{n} places left', 'ride.full' => 'Fully booked',
    'ride.you_confirmed_short' => 'You’re in', 'ride.you_waitlist_short' => 'You’re on the waiting list',
    'ride.not_editable' => 'This ride can no longer be changed.',
    'ride.pick_tour_text' => 'Which route are you riding? Listed are public routes and your crews’ routes. Private routes don’t appear – set them to “My crew” or “All” first.',
    'ride.no_tours' => 'There’s no route yet that you can offer as a ride. Plan a route first.',
    'ride.tour' => 'Route', 'ride.continue' => 'Continue', 'ride.other_tour' => 'choose another route',
    'ride.map_hint' => 'Click the map to mark the meeting point. You can drag the pin.',
    'ride.meeting_at_start' => 'Meeting point = start of the route', 'ride.meeting_clear' => 'Remove pin',
    'ride.meeting_point' => 'Meeting point', 'ride.meeting_hint' => 'So people can find you, e.g. “car park by the river, next to the kiosk”.',
    'ride.title_label' => 'Ride title', 'ride.date' => 'Date', 'ride.time' => 'Time (meet-up)',
    'ride.capacity' => 'Participant limit', 'ride.capacity_hint' => 'Including you. Required – better start small.',
    'ride.waitlist_enabled' => 'Waiting list once all places are taken',
    'ride.audience' => 'Who is it for?', 'ride.audience_crew' => 'Crew: {name}', 'ride.audience_public' => 'All logged-in riders (public)',
    'ride.audience_hint' => 'Crew rides show up on the crew page and get their own topic in crew talk.',
    'ride.description' => 'Description', 'ride.description_hint' => 'Breaks, destination, what to bring. Blank line for paragraphs, **bold**, - list.',
    'ride.stvo29_confirm' => 'From {n} participants: I have checked whether this ride needs a permit from the road traffic authority under Section 29 StVO and will take care of it.',
    'ride.road_legal_organizer' => 'I ride a road-legal, insured e-scooter myself and only take riders who do the same.',
    'ride.photo_consent' => 'Photos and videos of me on this ride are fine and may be shared with the participants and in the crew. (voluntary, can be changed any time)',
    'ride.organizer_note' => 'You are the organiser: you are signed up automatically and cancel the ride on ElTouro if it doesn’t take place. ElTouro does not organise the ride.',
    'ride.save' => 'Save', 'ride.publish' => 'Publish ride',
    'ride.error_title' => 'Please give the ride a title (at least 3 characters).',
    'ride.error_date' => 'Please enter a valid date and time.',
    'ride.error_date_range' => 'The date must be in the future and at most a year away.',
    'ride.error_meeting' => 'Please describe the meeting point.',
    'ride.error_capacity' => 'The participant limit must be between {min} and {max}.',
    'ride.error_capacity_below' => '{n} riders have already signed up – the limit can’t be lower.',
    'ride.error_stvo29' => 'From {n} participants you need to confirm that you checked the permit requirement under Section 29 StVO.',
    'ride.error_audience' => 'Please choose one of your crews or “public”.',
    'ride.error_tour_visibility' => 'Not all participants could see this route. A public ride needs a public route; a crew ride a public route or one of this crew.',
    'ride.error_road_legal' => 'A road-legal, insured e-scooter is a must – please confirm.',
    'ride.error_cancel_reason' => 'Please give a short reason for cancelling.',
    'ride.saved' => 'Saved.', 'ride.saved_notified' => 'Saved. Everyone signed up gets an email about the change.',
    'ride.created' => 'Your ride is published.',
    'ride.talk_title' => 'Ride: {title} ({date})',
    'ride.talk_announcement' => "**{when}**\nMeeting point: {meeting}\nRoute: {tour} ({km})\nPlaces: {capacity}\n\n[Open ride and sign up]({link})",
    'ride.talk_changed' => "**Changed:** The ride is now on {when}, meeting point: {meeting}.",
    'ride.talk_cancelled' => "**Cancelled:** {reason}",
    'ride.signup_confirmed' => 'You’re in! See you at the meeting point.', 'ride.signup_waitlist' => 'You’re on the waiting list. If a place frees up, you move up automatically and get an email.',
    'ride.signup_full' => 'Sorry, the ride is fully booked.', 'ride.signup_closed' => 'Sign-up for this ride is closed.',
    'ride.signup_already' => 'You’re already signed up.', 'ride.withdrawn' => 'You’ve cancelled your sign-up.', 'ride.photo_saved' => 'Your photo preference is saved.',
    'ride.cancelled_ok' => 'The ride is cancelled. Everyone signed up gets an email.',
    'ride.is_cancelled' => 'This ride was cancelled: {reason}', 'ride.is_past' => 'This ride has already taken place.',
    'ride.places' => 'Places', 'ride.free_of' => '{n} of {max} left', 'ride.waitlist_count' => '{n} on the waiting list',
    'ride.to_tour' => 'Open route', 'ride.to_talk' => 'Discuss in crew talk', 'ride.to_ride' => 'Open ride',
    'ride.tour_gone' => 'The route of this ride was deleted.',
    'ride.rule_organizer' => 'This ride is organised by {name}, not by ElTouro.',
    'ride.rule_road_legal' => 'Only with a road-legal, insured e-scooter.',
    'ride.rule_own_risk' => 'Everyone rides at their own risk. Difficulty and riding style are the organiser’s assessment.',
    'ride.rule_signs' => 'The route is a suggestion – road signs and traffic law on site always take priority.',
    'ride.rule_stvo29' => 'The organiser has confirmed checking the permit requirement under Section 29 StVO for this group size.',
    'ride.you_organize' => 'You’re organising this ride.', 'ride.you_confirmed' => 'You’re signed up.', 'ride.you_waitlist' => 'You’re number {n} on the waiting list.',
    'ride.photo_save' => 'Save', 'ride.withdraw' => 'Cancel my sign-up',
    'ride.signup_title' => 'Ride along', 'ride.waitlist_title' => 'Fully booked – join the waiting list',
    'ride.full_no_waitlist' => 'All places are taken and there’s no waiting list.',
    'ride.road_legal_rider' => 'I ride a road-legal, insured e-scooter.',
    'ride.photo_hint' => 'You can ride along without ticking this. Others will then see “no photos” next to your name.',
    'ride.signup' => 'Sign up', 'ride.join_waitlist' => 'Join waiting list',
    'ride.participants' => 'Who’s riding?', 'ride.participants_hidden' => '{n} riders have signed up. Only participants see the names.',
    'ride.organizer' => 'Organiser', 'ride.on_waitlist' => 'Waiting list', 'ride.no_photo' => 'no photos', 'ride.no_photo_title' => 'Please don’t photograph or film',
    'ride.cancel_title' => 'Cancel ride', 'ride.cancel_text' => 'Everyone signed up and on the waiting list gets an email with your reason.',
    'ride.cancel_reason' => 'Reason', 'ride.cancel_button' => 'Cancel ride',

    'mail.ride_promoted_subject' => 'You’re in: {title}',
    'mail.ride_promoted_text' => "Hi {name},\n\na place has freed up – you moved up from the waiting list and are now signed up for:\n\n{title}\n{when}\nMeeting point: {meeting}\n\n{link}\n\nIf you can’t make it after all, please cancel there so the next rider can move up.\n\nThe ElTouro team",
    'mail.ride_changed_subject' => 'Changed: {title}',
    'mail.ride_changed_text' => "Hi {name},\n\nsomething has changed for your ride:\n\n{title}\n{when}\nMeeting point: {meeting}\n\n{link}\n\nDoesn’t work for you any more? Please cancel your sign-up there.\n\nThe ElTouro team",
    'mail.ride_cancelled_subject' => 'Cancelled: {title}',
    'mail.ride_cancelled_text' => "Hi {name},\n\nthe ride “{title}” on {when} has been cancelled.\n\nReason: {reason}\n\n{link}\n\nThe ElTouro team",
],
];
